import bcrypt from "bcrypt";

const data = {
  users: [
    {
      name: "Vengadesh",
      email: "vengadesh@test.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "testuser",
      email: "test@test.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  product: [
    {     
      name: "Nikie Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "high quality product",
      countInStock: 10,
    },
    {    
      name: "Medium Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 450,
      brand: "Mike",
      rating: "3.5",
      numReviews: "100",
      description: "Medium quality product",
      countInStock: 20,
    },
    {     
      name: "Cashoo Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 170,
      brand: "Bike",
      rating: "2.5",
      numReviews: "110",
      description: "quality product",
      countInStock: 0,
    },
    {      
      name: "Poom Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 1558,
      brand: "Tike",
      rating: "5",
      numReviews: "1050",
      description: "high quality product",
      countInStock: 30,
    },
    {      
      re: "",
      name: "Tike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 2320,
      brand: "Nike",
      rating: "3.5",
      numReviews: "10",
      description: "low quality product",
      countInStock: 4,
    },
    {
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 4520,
      brand: "Adidas",
      rating: "4.5",
      numReviews: "10",
      description: "high Adidas product",
      countInStock: 100,
    },
    {      
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: "2.5",
      numReviews: "50",
      description: "quality product",
      countInStock: 0,
    },
  ],
};

export default data;
